version: '3.8'

services:
  benchmark:
    build: .
    container_name: benchmark-engine
    ports:
      - "8000:8000"  # API
      - "8501:8501"  # Streamlit UI
    volumes:
      - .:/app
    environment:
      - API_URL=http://localhost:8000
      - SPARK_HOME=/usr/local/lib/python3.9/site-packages/pyspark
      - PYTHONPATH=/usr/local/lib/python3.9/site-packages
      - SPARK_DRIVER_MEMORY=2g
      - SPARK_EXECUTOR_MEMORY=2g
      - SPARK_WORKER_MEMORY=2g
    deploy:
      resources:
        limits:
          memory: 4G
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    command: ["sh", "-c", "uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload & streamlit run src/streamlit_app.py --server.port 8501 --server.address 0.0.0.0 --server.runOnSave true"]
    networks:
      - benchmark-network

networks:
  benchmark-network:
    driver: bridge
