version: '3.8'

services:
  benchmark:
    build: .
    container_name: benchmark-engine
    ports:
      - "8000:8000"  # API
      - "8501:8501"  # Streamlit UI
    volumes:
      - .:/app
    environment:
      - API_URL=http://localhost:8000
    networks:
      - benchmark-network

networks:
  benchmark-network:
    driver: bridge
